ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: metrics-app.host
      paths: ["/"]
enableMonigtoring: "false"
alertRules:
  - alert: VersionAlert
    expr: version{job="metrics-app"} != 1

  - alert: NoTrafficFlowing
    expr: rate(http_requests_total{job="metrics-app", code=~"2[0-9]{2}"}[5m]) < 100

  - alert: 90%ile of requests processed in less then 0.005 sec
    expr: histogram_quantile(0.9, http_request_duration_seconds_bucket{job="metrics-app"}) > 0.005

  - alert: 99%ile of requests processed in less then 0.05 sec
    expr: histogram_quantile(0.9, http_request_duration_seconds_bucket{job="metrics-app"}) > 0.05

  - alert: SLO - Error requests to overall request ratio shouldn't exceed 5%
    expr: sli:errors_per_request:ratio_rate5m{job="metrics-app"} * 100 > 5

recordRules:
  - record: sli:errors_per_request:ratio_rate5m
    expr: (rate(http_requests_total{code!~"2[0-9]{2}",job="metrics-app"}[5m])) / ignoring(code) (sum without(code) (rate(http_requests_total{code=~"[0-9]{3}",job="metrics-app"}[5m])))

